server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: http://www.baeldung.com
        predicates:
        - Path=/baeldung
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  application:
    name: gateway

            
management:
  endpoints:
    web:
      exposure:
        include: "*"

        
# Register with Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




